# Generated by Django 5.2 on 2025-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='response_body',
            field=models.TextField(default='{"status": "ok"}'),
        ),
        migrations.AddField(
            model_name='session',
            name='response_headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='response_status',
            field=models.IntegerField(default=200),
        ),
    ]
